# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='recipes.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(1, 'simple'), (2, 'normal'), (3, 'hard')], default=2, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='One ingredient per line', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_of_portions',
            field=models.PositiveIntegerField(verbose_name='Number of portions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='recipes', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(verbose_name='Preparation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_for_preparation',
            field=models.IntegerField(blank=True, help_text='Time in minutes', null=True, verbose_name='Time for preparation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
